export const DefaultTableLocalization = {
  dataLoading: "Loading",
  defaultFilterSearchPlaceholder: "Type here to search",
  alternativeFilterSearchPlaceholder: "Search",
  filterReset: "Reset filter",
  filterLoading: "Loading",
  dataEmpty: "No Data",
  filterEmpty: "No Result",
  paginationPageSize: "Page size",
  paginationNext: "Next",
  paginationPrev: "Previous",
  paginationTotalCount: "result(s)",
  filterButtonTitle: "Filter",
  ascendingSortTitle: "Ascending sort",
  descendingSortTitle: "Descending sort",
  clearSortTitle: "Clear",
  rowExpandTitle: "Expand",
  rowShrinkTitle: "Shrink",
  columnVisibilityTitle: "Column visibility",
};
