import { TableLocalizationType } from "../types/Table";

export const DefaultTableLocalization: TableLocalizationType = {
  dataLoading: "Loading",
  filterSearchPlaceholder: "Search",
  filterLoading: "Loading",
  dataEmpty: "No Data",
  filterEmpty: "No Result",
  paginationPageSize: "Page size",
  paginationNext: "Next",
  paginationPrev: "Previous",
  paginationTotalCount: "result(s)",
  filterButtonTitle: "Filter",
  ascendingSortTitle: "Ascending sort",
  descendingSortTitle: "Descending sort",
  clearSortTitle: "Clear",
  rowExpandTitle: "Expand",
  rowShrinkTitle: "Shrink",
  columnVisibilityTitle: "Column visibility",
  rowsSelectedTitle: "rows selected",
  selectOptionsLoading: "Loading options",
  menuTitle: "Menu",
  hideColumn: "Hide",
  pinColumnToLeft: "Pin to left",
  pinColumnToRight: "Pin to right",
  unpinColumn: "Unpin",
};
