import { TableLocalizationType } from "../types/Table";

export const DefaultTableLocalization: TableLocalizationType = {
  dataLoading: "Loading",
  filterInputPlaceholder: "Search",
  filterDatePlaceholder: "month/day/year",
  filterLoading: "Loading",
  clearFilers: "Clear filters",
  dataEmpty: "No Data",
  filterEmpty: "No Result",
  paginationPageSize: "Page size",
  paginationNext: "Next",
  paginationPrev: "Previous",
  paginationTotalCount: "result(s)",
  filterButtonTitle: "Filter",
  ascendingSortTitle: "Ascending sort",
  descendingSortTitle: "Descending sort",
  clearSortTitle: "Clear",
  rowExpandTitle: "Expand",
  rowShrinkTitle: "Shrink",
  columnVisibilityTitle: "Column visibility",
  rowsSelectedTitle: "rows selected",
  selectOptionsLoading: "Loading options",
  selectPlaceholder: "Select",
  menuTitle: "Menu",
  hideColumn: "Hide",
  pinColumnToLeft: "Pin to left",
  pinColumnToRight: "Pin to right",
  unpinColumn: "Unpin",
  filterContains: "Contains",
  filterBetween: "Between",
  filterBetweenInclusive: "Between inclusive",
  filterEndsWith: "Ends with",
  filterEquals: "Equals",
  filterGreaterThan: "Greater than",
  filterGreaterThanOrEqualTo: "Greater than or equal",
  filterLessThan: "Less than",
  filterLessThanOrEqualTo: "Less than or equal",
  filterNotEquals: "Not equals",
  filterStartsWith: "Starts with",
};
